### ISSUE TITLE
RGB-D image from ROS on Unity

### ISSUE THREAD

**Issue by dvargasfr** [siemens/ros-sharp#152]
Hi!

I am trying to visualize RGB-D images from Asus Xtion Pro on Unity using ROS#. 
Main problem is to understand and correctly process data structure of PointCloud2 messages. 
An example of a message:

```
header: 
  seq: 9421
  stamp: 
    secs: 1544456358
    nsecs: 530346386
  frame_id: "camera_depth_optical_frame"
height: 480
width: 640
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
is_bigendian: False
point_step: 16
row_step: 10240
data: [29, 82, 110, 192, 214, 116, 50, 192, 148, 24, 216, 64, 0, 0, 0, 0, 31, 144, 109, 192, 214, 116, 50, 192, 148, 24, 216, 64, 0, 0, 0, 0, ... ]
is_dense: False
```
Data is uint array, and point step is 16, so every 16 uints of data correspond to XYZ coordinates of a pointcloud point (each coordinate represented by 4 uints).
First step is do is to convert these uint data to hexadecimal.
Due to `is_bigendian=False` data reversing is needed. As shown above, last four uints of each point are zeros, so I am reversing each uint[4] data array corresponding to XYZ coordinates, not uint[16] data array corresponding to each point.
And last step consist of convert that hexa string to float and get float values for every XYZ points.

But after that I am not getting reasonable values to display a pointcloud corresponding to the real one. I'd like to know if the methon I followed is correct, if there is any simpler way, or if anyone have some function code or clue which could guide me.

Thanks a lot!
